#!/bin/sh
wget http://feeds.delicious.com/rss/retiman/401k
wget http://feeds.delicious.com/rss/retiman/acegi
wget http://feeds.delicious.com/rss/retiman/ajax
wget http://feeds.delicious.com/rss/retiman/algorithms
wget http://feeds.delicious.com/rss/retiman/anime
wget http://feeds.delicious.com/rss/retiman/anmaniacs
wget http://feeds.delicious.com/rss/retiman/ant
wget http://feeds.delicious.com/rss/retiman/antitrust
wget http://feeds.delicious.com/rss/retiman/apache
wget http://feeds.delicious.com/rss/retiman/appfuse
wget http://feeds.delicious.com/rss/retiman/apple
wget http://feeds.delicious.com/rss/retiman/asian
wget http://feeds.delicious.com/rss/retiman/asimov
wget http://feeds.delicious.com/rss/retiman/at&t
wget http://feeds.delicious.com/rss/retiman/atheism
wget http://feeds.delicious.com/rss/retiman/ati
wget http://feeds.delicious.com/rss/retiman/auction
wget http://feeds.delicious.com/rss/retiman/backup
wget http://feeds.delicious.com/rss/retiman/bash
wget http://feeds.delicious.com/rss/retiman/bbcode
wget http://feeds.delicious.com/rss/retiman/bible
wget http://feeds.delicious.com/rss/retiman/biology
wget http://feeds.delicious.com/rss/retiman/bios
wget http://feeds.delicious.com/rss/retiman/bittorrent
wget http://feeds.delicious.com/rss/retiman/bjj
wget http://feeds.delicious.com/rss/retiman/bluray
wget http://feeds.delicious.com/rss/retiman/books
wget http://feeds.delicious.com/rss/retiman/broadcom
wget http://feeds.delicious.com/rss/retiman/bugs
wget http://feeds.delicious.com/rss/retiman/c++
wget http://feeds.delicious.com/rss/retiman/caching
wget http://feeds.delicious.com/rss/retiman/callofduty4
wget http://feeds.delicious.com/rss/retiman/car
wget http://feeds.delicious.com/rss/retiman/centos
wget http://feeds.delicious.com/rss/retiman/chess
wget http://feeds.delicious.com/rss/retiman/china
wget http://feeds.delicious.com/rss/retiman/cleaning
wget http://feeds.delicious.com/rss/retiman/clojure
wget http://feeds.delicious.com/rss/retiman/clustering
wget http://feeds.delicious.com/rss/retiman/cms
wget http://feeds.delicious.com/rss/retiman/codeanalysis
wget http://feeds.delicious.com/rss/retiman/codebreaker
wget http://feeds.delicious.com/rss/retiman/coin
wget http://feeds.delicious.com/rss/retiman/color
wget http://feeds.delicious.com/rss/retiman/compilers
wget http://feeds.delicious.com/rss/retiman/compiz
wget http://feeds.delicious.com/rss/retiman/complex
wget http://feeds.delicious.com/rss/retiman/computer
wget http://feeds.delicious.com/rss/retiman/console
wget http://feeds.delicious.com/rss/retiman/converter
wget http://feeds.delicious.com/rss/retiman/cool
wget http://feeds.delicious.com/rss/retiman/cosplay
wget http://feeds.delicious.com/rss/retiman/counting
wget http://feeds.delicious.com/rss/retiman/cpu
wget http://feeds.delicious.com/rss/retiman/creationism
wget http://feeds.delicious.com/rss/retiman/cryptography
wget http://feeds.delicious.com/rss/retiman/css
wget http://feeds.delicious.com/rss/retiman/database
wget http://feeds.delicious.com/rss/retiman/db2
wget http://feeds.delicious.com/rss/retiman/ddwrt
wget http://feeds.delicious.com/rss/retiman/design
wget http://feeds.delicious.com/rss/retiman/development
wget http://feeds.delicious.com/rss/retiman/dinosaur
wget http://feeds.delicious.com/rss/retiman/dmca
wget http://feeds.delicious.com/rss/retiman/dns
wget http://feeds.delicious.com/rss/retiman/dos
wget http://feeds.delicious.com/rss/retiman/draft
wget http://feeds.delicious.com/rss/retiman/drm
wget http://feeds.delicious.com/rss/retiman/ds
wget http://feeds.delicious.com/rss/retiman/dumbass
wget http://feeds.delicious.com/rss/retiman/dvd
wget http://feeds.delicious.com/rss/retiman/ebay
wget http://feeds.delicious.com/rss/retiman/eclipse
wget http://feeds.delicious.com/rss/retiman/education
wget http://feeds.delicious.com/rss/retiman/ehcache
wget http://feeds.delicious.com/rss/retiman/entertainment
wget http://feeds.delicious.com/rss/retiman/erlang
wget http://feeds.delicious.com/rss/retiman/evil
wget http://feeds.delicious.com/rss/retiman/evolution
wget http://feeds.delicious.com/rss/retiman/facebook
wget http://feeds.delicious.com/rss/retiman/fan
wget http://feeds.delicious.com/rss/retiman/fbi
wget http://feeds.delicious.com/rss/retiman/fin
wget http://feeds.delicious.com/rss/retiman/finalfantasy
wget http://feeds.delicious.com/rss/retiman/firefox
wget http://feeds.delicious.com/rss/retiman/font
wget http://feeds.delicious.com/rss/retiman/frameworks
wget http://feeds.delicious.com/rss/retiman/friend
wget http://feeds.delicious.com/rss/retiman/funny
wget http://feeds.delicious.com/rss/retiman/gaming
wget http://feeds.delicious.com/rss/retiman/gdm
wget http://feeds.delicious.com/rss/retiman/gender
wget http://feeds.delicious.com/rss/retiman/generics
wget http://feeds.delicious.com/rss/retiman/genetic
wget http://feeds.delicious.com/rss/retiman/gentoo
wget http://feeds.delicious.com/rss/retiman/gifts
wget http://feeds.delicious.com/rss/retiman/git
wget http://feeds.delicious.com/rss/retiman/gnome
wget http://feeds.delicious.com/rss/retiman/google
wget http://feeds.delicious.com/rss/retiman/gp2x
wget http://feeds.delicious.com/rss/retiman/graduate
wget http://feeds.delicious.com/rss/retiman/gre
wget http://feeds.delicious.com/rss/retiman/greasemonkey
wget http://feeds.delicious.com/rss/retiman/guice
wget http://feeds.delicious.com/rss/retiman/gutsy
wget http://feeds.delicious.com/rss/retiman/hack
wget http://feeds.delicious.com/rss/retiman/hardware
wget http://feeds.delicious.com/rss/retiman/hardy
wget http://feeds.delicious.com/rss/retiman/haskell
wget http://feeds.delicious.com/rss/retiman/hdmi
wget http://feeds.delicious.com/rss/retiman/health
wget http://feeds.delicious.com/rss/retiman/hibernate
wget http://feeds.delicious.com/rss/retiman/highlighter
wget http://feeds.delicious.com/rss/retiman/history
wget http://feeds.delicious.com/rss/retiman/home
wget http://feeds.delicious.com/rss/retiman/honda
wget http://feeds.delicious.com/rss/retiman/howstuffworks
wget http://feeds.delicious.com/rss/retiman/howto
wget http://feeds.delicious.com/rss/retiman/html
wget http://feeds.delicious.com/rss/retiman/i18n
wget http://feeds.delicious.com/rss/retiman/ibm
wget http://feeds.delicious.com/rss/retiman/idea
wget http://feeds.delicious.com/rss/retiman/idiocy
wget http://feeds.delicious.com/rss/retiman/image
wget http://feeds.delicious.com/rss/retiman/innumeracy
wget http://feeds.delicious.com/rss/retiman/insurance
wget http://feeds.delicious.com/rss/retiman/int
wget http://feeds.delicious.com/rss/retiman/internet
wget http://feeds.delicious.com/rss/retiman/interviews
wget http://feeds.delicious.com/rss/retiman/investing
wget http://feeds.delicious.com/rss/retiman/iphone
wget http://feeds.delicious.com/rss/retiman/ipod
wget http://feeds.delicious.com/rss/retiman/iraq
wget http://feeds.delicious.com/rss/retiman/jai
wget http://feeds.delicious.com/rss/retiman/japan
wget http://feeds.delicious.com/rss/retiman/java
wget http://feeds.delicious.com/rss/retiman/javascript
wget http://feeds.delicious.com/rss/retiman/jee
wget http://feeds.delicious.com/rss/retiman/jmx
wget http://feeds.delicious.com/rss/retiman/job
wget http://feeds.delicious.com/rss/retiman/journals
wget http://feeds.delicious.com/rss/retiman/kde
wget http://feeds.delicious.com/rss/retiman/kdm
wget http://feeds.delicious.com/rss/retiman/keyboard
wget http://feeds.delicious.com/rss/retiman/korea
wget http://feeds.delicious.com/rss/retiman/languages
wget http://feeds.delicious.com/rss/retiman/laptop
wget http://feeds.delicious.com/rss/retiman/lasik
wget http://feeds.delicious.com/rss/retiman/law
wget http://feeds.delicious.com/rss/retiman/lift
wget http://feeds.delicious.com/rss/retiman/lighttpd
wget http://feeds.delicious.com/rss/retiman/linguistics
wget http://feeds.delicious.com/rss/retiman/linux
wget http://feeds.delicious.com/rss/retiman/lisp
wget http://feeds.delicious.com/rss/retiman/local
wget http://feeds.delicious.com/rss/retiman/lockpicking
wget http://feeds.delicious.com/rss/retiman/log4j
wget http://feeds.delicious.com/rss/retiman/maemo
wget http://feeds.delicious.com/rss/retiman/mapreduce
wget http://feeds.delicious.com/rss/retiman/math
wget http://feeds.delicious.com/rss/retiman/maven
wget http://feeds.delicious.com/rss/retiman/maxima
wget http://feeds.delicious.com/rss/retiman/mgs4
wget http://feeds.delicious.com/rss/retiman/microsoft
wget http://feeds.delicious.com/rss/retiman/minesweeper
wget http://feeds.delicious.com/rss/retiman/minformix
wget http://feeds.delicious.com/rss/retiman/mma
wget http://feeds.delicious.com/rss/retiman/monads
wget http://feeds.delicious.com/rss/retiman/money
wget http://feeds.delicious.com/rss/retiman/mp3
wget http://feeds.delicious.com/rss/retiman/mplayer
wget http://feeds.delicious.com/rss/retiman/mtg
wget http://feeds.delicious.com/rss/retiman/music
wget http://feeds.delicious.com/rss/retiman/mysql
wget http://feeds.delicious.com/rss/retiman/n810
wget http://feeds.delicious.com/rss/retiman/nasubi
wget http://feeds.delicious.com/rss/retiman/navi
wget http://feeds.delicious.com/rss/retiman/nes
wget http://feeds.delicious.com/rss/retiman/netbeans
wget http://feeds.delicious.com/rss/retiman/netflix
wget http://feeds.delicious.com/rss/retiman/networking
wget http://feeds.delicious.com/rss/retiman/news
wget http://feeds.delicious.com/rss/retiman/nfs
wget http://feeds.delicious.com/rss/retiman/nmapplet
wget http://feeds.delicious.com/rss/retiman/nsfw
wget http://feeds.delicious.com/rss/retiman/obfuscated
wget http://feeds.delicious.com/rss/retiman/octopus
wget http://feeds.delicious.com/rss/retiman/osx
wget http://feeds.delicious.com/rss/retiman/p2p
wget http://feeds.delicious.com/rss/retiman/patterns
wget http://feeds.delicious.com/rss/retiman/paypal
wget http://feeds.delicious.com/rss/retiman/pgp
wget http://feeds.delicious.com/rss/retiman/phone
wget http://feeds.delicious.com/rss/retiman/photography
wget http://feeds.delicious.com/rss/retiman/photoshop
wget http://feeds.delicious.com/rss/retiman/php
wget http://feeds.delicious.com/rss/retiman/physics
wget http://feeds.delicious.com/rss/retiman/piracy
wget http://feeds.delicious.com/rss/retiman/pmp
wget http://feeds.delicious.com/rss/retiman/poker
wget http://feeds.delicious.com/rss/retiman/politics
wget http://feeds.delicious.com/rss/retiman/primes
wget http://feeds.delicious.com/rss/retiman/privacy
wget http://feeds.delicious.com/rss/retiman/programming
wget http://feeds.delicious.com/rss/retiman/proxy
wget http://feeds.delicious.com/rss/retiman/ps2
wget http://feeds.delicious.com/rss/retiman/ps3
wget http://feeds.delicious.com/rss/retiman/psp
wget http://feeds.delicious.com/rss/retiman/psx
wget http://feeds.delicious.com/rss/retiman/psychology
wget http://feeds.delicious.com/rss/retiman/puzzles
wget http://feeds.delicious.com/rss/retiman/python
wget http://feeds.delicious.com/rss/retiman/quantum
wget http://feeds.delicious.com/rss/retiman/quartz
wget http://feeds.delicious.com/rss/retiman/raid
wget http://feeds.delicious.com/rss/retiman/rails
wget http://feeds.delicious.com/rss/retiman/reference
wget http://feeds.delicious.com/rss/retiman/relationships
wget http://feeds.delicious.com/rss/retiman/religion
wget http://feeds.delicious.com/rss/retiman/resin
wget http://feeds.delicious.com/rss/retiman/retard
wget http://feeds.delicious.com/rss/retiman/ronpaul
wget http://feeds.delicious.com/rss/retiman/router
wget http://feeds.delicious.com/rss/retiman/rsync
wget http://feeds.delicious.com/rss/retiman/ruby
wget http://feeds.delicious.com/rss/retiman/samba
wget http://feeds.delicious.com/rss/retiman/savegame
wget http://feeds.delicious.com/rss/retiman/scala
wget http://feeds.delicious.com/rss/retiman/scary
wget http://feeds.delicious.com/rss/retiman/school
wget http://feeds.delicious.com/rss/retiman/science
wget http://feeds.delicious.com/rss/retiman/scim
wget http://feeds.delicious.com/rss/retiman/scm
wget http://feeds.delicious.com/rss/retiman/screen
wget http://feeds.delicious.com/rss/retiman/scripting
wget http://feeds.delicious.com/rss/retiman/security
wget http://feeds.delicious.com/rss/retiman/selinux
wget http://feeds.delicious.com/rss/retiman/serials
wget http://feeds.delicious.com/rss/retiman/shell
wget http://feeds.delicious.com/rss/retiman/snes
wget http://feeds.delicious.com/rss/retiman/software
wget http://feeds.delicious.com/rss/retiman/sony
wget http://feeds.delicious.com/rss/retiman/source
wget http://feeds.delicious.com/rss/retiman/spring
wget http://feeds.delicious.com/rss/retiman/sql
wget http://feeds.delicious.com/rss/retiman/ssh
wget http://feeds.delicious.com/rss/retiman/steam
wget http://feeds.delicious.com/rss/retiman/stickinbutt
wget http://feeds.delicious.com/rss/retiman/stocks
wget http://feeds.delicious.com/rss/retiman/stress
wget http://feeds.delicious.com/rss/retiman/subversion
wget http://feeds.delicious.com/rss/retiman/swiftfox
wget http://feeds.delicious.com/rss/retiman/syntax
wget http://feeds.delicious.com/rss/retiman/system:unfiled
wget http://feeds.delicious.com/rss/retiman/taxes
wget http://feeds.delicious.com/rss/retiman/technology
wget http://feeds.delicious.com/rss/retiman/testing
wget http://feeds.delicious.com/rss/retiman/thinkpad
wget http://feeds.delicious.com/rss/retiman/tips
wget http://feeds.delicious.com/rss/retiman/tomcat
wget http://feeds.delicious.com/rss/retiman/tor
wget http://feeds.delicious.com/rss/retiman/trac
wget http://feeds.delicious.com/rss/retiman/tv
wget http://feeds.delicious.com/rss/retiman/ubuntu
wget http://feeds.delicious.com/rss/retiman/unicode
wget http://feeds.delicious.com/rss/retiman/upload
wget http://feeds.delicious.com/rss/retiman/url
wget http://feeds.delicious.com/rss/retiman/usc
wget http://feeds.delicious.com/rss/retiman/video
wget http://feeds.delicious.com/rss/retiman/vim
wget http://feeds.delicious.com/rss/retiman/vista
wget http://feeds.delicious.com/rss/retiman/vmware
wget http://feeds.delicious.com/rss/retiman/w3c
wget http://feeds.delicious.com/rss/retiman/war
wget http://feeds.delicious.com/rss/retiman/web
wget http://feeds.delicious.com/rss/retiman/weird
wget http://feeds.delicious.com/rss/retiman/widgets
wget http://feeds.delicious.com/rss/retiman/wifi
wget http://feeds.delicious.com/rss/retiman/wii
wget http://feeds.delicious.com/rss/retiman/windows
wget http://feeds.delicious.com/rss/retiman/wine
wget http://feeds.delicious.com/rss/retiman/women
wget http://feeds.delicious.com/rss/retiman/worldofwarcraft
wget http://feeds.delicious.com/rss/retiman/writing
wget http://feeds.delicious.com/rss/retiman/wtf
wget http://feeds.delicious.com/rss/retiman/xfce
wget http://feeds.delicious.com/rss/retiman/xml
wget http://feeds.delicious.com/rss/retiman/xorg.conf
